apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: laravel-runtime-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: laravel-platform
  source:
    repoURL: https://github.com/tconuorah/laravel-eks-gitops-repo.git
    targetRevision: main
    path: workloads/dev/laravel
  destination:
    server: https://kubernetes.default.svc
    namespace: laravel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
