apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: laravel-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  sourceRepos:
    - https://github.com/tconuorah/laravel-eks-gitops-repo.git
    - https://github.com/tconuorah/laravel-eks-deploy-gitops.git
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: external-secrets
      server: https://kubernetes.default.svc
    - namespace: laravel
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
